services:
  db:
    container_name: gestor-db
    image: postgres:18
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db_gestor
    ports:
      - "15432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    restart: unless-stopped
    

  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev   
    container_name: gestor-backend-dev
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://gestor-db:5432/db_gestor
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_DEVTOOLS_RESTART_ENABLED: "true"
    volumes:
      - ./:/app                     
      - ~/.m2:/root/.m2              
    ports:
      - "9090:9090"
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: gestor-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"  
    depends_on:
      - db

volumes:
  postgres_data:
